"""canvas_curso_id y canvas_url en guias

Revision ID: 8d6345250b7a
Revises: d944c06ef839
Create Date: 2026-08-08 19:41:17.703571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6345250b7a'
down_revision: Union[str, None] = 'd944c06ef839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guias', sa.Column('canvas_curso_id', sa.Integer(), nullable=True))
    op.add_column('guias', sa.Column('canvas_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guias', 'canvas_url')
    op.drop_column('guias', 'canvas_curso_id')
    # ### end Alembic commands ###
