"""esquema inicial

Revision ID: d944c06ef839
Revises: 
Create Date: 2026-08-07 00:41:02.700484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd944c06ef839'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facultades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_codigo'), 'roles', ['codigo'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_table('guias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_banner', sa.String(length=30), nullable=False),
    sa.Column('codigo_componente', sa.String(length=50), nullable=True),
    sa.Column('nombre_asignatura', sa.String(length=300), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('total_semanas', sa.Integer(), nullable=False),
    sa.Column('facultad_id', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['facultad_id'], ['facultades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guias_autor_id'), 'guias', ['autor_id'], unique=False)
    op.create_index(op.f('ix_guias_codigo_banner'), 'guias', ['codigo_banner'], unique=False)
    op.create_index(op.f('ix_guias_estado'), 'guias', ['estado'], unique=False)
    op.create_index(op.f('ix_guias_periodo'), 'guias', ['periodo'], unique=False)
    op.create_table('registro_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_auditoria_accion'), 'registro_auditoria', ['accion'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_creado_en'), 'registro_auditoria', ['creado_en'], unique=False)
    op.create_index(op.f('ix_registro_auditoria_usuario_id'), 'registro_auditoria', ['usuario_id'], unique=False)
    op.create_table('usuarios_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('ambito_tipo', sa.String(length=20), nullable=False),
    sa.Column('ambito_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'rol_id', 'ambito_tipo', 'ambito_id', name='uq_usuario_rol_ambito')
    )
    op.create_index(op.f('ix_usuarios_roles_rol_id'), 'usuarios_roles', ['rol_id'], unique=False)
    op.create_index(op.f('ix_usuarios_roles_usuario_id'), 'usuarios_roles', ['usuario_id'], unique=False)
    op.create_table('asignaciones_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guia_id', sa.Integer(), nullable=False),
    sa.Column('revisor_id', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('asignada_por', sa.Integer(), nullable=False),
    sa.Column('asignada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resuelta_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asignada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['guia_id'], ['guias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revisor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_revision_guia_id'), 'asignaciones_revision', ['guia_id'], unique=False)
    op.create_index(op.f('ix_asignaciones_revision_revisor_id'), 'asignaciones_revision', ['revisor_id'], unique=False)
    op.create_table('cuotas_pagina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guia_id', sa.Integer(), nullable=False),
    sa.Column('pagina_id', sa.String(length=50), nullable=False),
    sa.Column('usadas', sa.Integer(), nullable=False),
    sa.Column('maximas', sa.Integer(), nullable=False),
    sa.Column('ampliada_por', sa.Integer(), nullable=True),
    sa.Column('ampliada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_ampliacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ampliada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['guia_id'], ['guias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guia_id', 'pagina_id', name='uq_cuota_guia_pagina')
    )
    op.create_index(op.f('ix_cuotas_pagina_guia_id'), 'cuotas_pagina', ['guia_id'], unique=False)
    op.create_table('solicitudes_generacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guia_id', sa.Integer(), nullable=False),
    sa.Column('solicitada_por', sa.Integer(), nullable=False),
    sa.Column('requerimientos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alcance', sa.String(length=20), nullable=False),
    sa.Column('pagina_id', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('progreso', sa.Integer(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('mensaje_error', sa.Text(), nullable=True),
    sa.Column('modelo_usado', sa.String(length=100), nullable=True),
    sa.Column('version_prompt', sa.String(length=50), nullable=True),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_salida', sa.Integer(), nullable=True),
    sa.Column('encolada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminada_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guia_id'], ['guias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitada_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_generacion_estado'), 'solicitudes_generacion', ['estado'], unique=False)
    op.create_index(op.f('ix_solicitudes_generacion_guia_id'), 'solicitudes_generacion', ['guia_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_generacion_solicitada_por'), 'solicitudes_generacion', ['solicitada_por'], unique=False)
    op.create_table('versiones_guia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guia_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=30), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=True),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version_esquema', sa.String(length=20), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('ruta_paquete', sa.String(length=500), nullable=True),
    sa.Column('semaforo', sa.String(length=20), nullable=True),
    sa.Column('alertas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('congelada', sa.Boolean(), nullable=False),
    sa.Column('es_actual', sa.Boolean(), nullable=False),
    sa.Column('creada_por', sa.Integer(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['guia_id'], ['guias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_generacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guia_id', 'numero', name='uq_version_guia_numero')
    )
    op.create_index(op.f('ix_versiones_guia_es_actual'), 'versiones_guia', ['es_actual'], unique=False)
    op.create_index(op.f('ix_versiones_guia_guia_id'), 'versiones_guia', ['guia_id'], unique=False)
    op.create_index(op.f('ix_versiones_guia_origen'), 'versiones_guia', ['origen'], unique=False)
    op.create_index(op.f('ix_versiones_guia_semaforo'), 'versiones_guia', ['semaforo'], unique=False)
    op.create_table('ediciones_bloque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('operacion', sa.String(length=40), nullable=False),
    sa.Column('bloque_id', sa.String(length=50), nullable=True),
    sa.Column('pagina_id', sa.String(length=50), nullable=True),
    sa.Column('antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('despues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('realizada_por', sa.Integer(), nullable=False),
    sa.Column('realizada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['realizada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versiones_guia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ediciones_bloque_bloque_id'), 'ediciones_bloque', ['bloque_id'], unique=False)
    op.create_index(op.f('ix_ediciones_bloque_operacion'), 'ediciones_bloque', ['operacion'], unique=False)
    op.create_index(op.f('ix_ediciones_bloque_realizada_por'), 'ediciones_bloque', ['realizada_por'], unique=False)
    op.create_index(op.f('ix_ediciones_bloque_version_id'), 'ediciones_bloque', ['version_id'], unique=False)
    op.create_table('recursos_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('referencia', sa.String(length=200), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('ancho', sa.Integer(), nullable=True),
    sa.Column('alto', sa.Integer(), nullable=True),
    sa.Column('texto_alternativo', sa.Text(), nullable=True),
    sa.Column('es_decorativa', sa.Boolean(), nullable=False),
    sa.Column('generado_por', sa.String(length=50), nullable=True),
    sa.Column('url_canvas', sa.String(length=500), nullable=True),
    sa.Column('file_id_canvas', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['versiones_guia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recursos_version_referencia'), 'recursos_version', ['referencia'], unique=False)
    op.create_index(op.f('ix_recursos_version_sha256'), 'recursos_version', ['sha256'], unique=False)
    op.create_index(op.f('ix_recursos_version_tipo'), 'recursos_version', ['tipo'], unique=False)
    op.create_index(op.f('ix_recursos_version_version_id'), 'recursos_version', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recursos_version_version_id'), table_name='recursos_version')
    op.drop_index(op.f('ix_recursos_version_tipo'), table_name='recursos_version')
    op.drop_index(op.f('ix_recursos_version_sha256'), table_name='recursos_version')
    op.drop_index(op.f('ix_recursos_version_referencia'), table_name='recursos_version')
    op.drop_table('recursos_version')
    op.drop_index(op.f('ix_ediciones_bloque_version_id'), table_name='ediciones_bloque')
    op.drop_index(op.f('ix_ediciones_bloque_realizada_por'), table_name='ediciones_bloque')
    op.drop_index(op.f('ix_ediciones_bloque_operacion'), table_name='ediciones_bloque')
    op.drop_index(op.f('ix_ediciones_bloque_bloque_id'), table_name='ediciones_bloque')
    op.drop_table('ediciones_bloque')
    op.drop_index(op.f('ix_versiones_guia_semaforo'), table_name='versiones_guia')
    op.drop_index(op.f('ix_versiones_guia_origen'), table_name='versiones_guia')
    op.drop_index(op.f('ix_versiones_guia_guia_id'), table_name='versiones_guia')
    op.drop_index(op.f('ix_versiones_guia_es_actual'), table_name='versiones_guia')
    op.drop_table('versiones_guia')
    op.drop_index(op.f('ix_solicitudes_generacion_solicitada_por'), table_name='solicitudes_generacion')
    op.drop_index(op.f('ix_solicitudes_generacion_guia_id'), table_name='solicitudes_generacion')
    op.drop_index(op.f('ix_solicitudes_generacion_estado'), table_name='solicitudes_generacion')
    op.drop_table('solicitudes_generacion')
    op.drop_index(op.f('ix_cuotas_pagina_guia_id'), table_name='cuotas_pagina')
    op.drop_table('cuotas_pagina')
    op.drop_index(op.f('ix_asignaciones_revision_revisor_id'), table_name='asignaciones_revision')
    op.drop_index(op.f('ix_asignaciones_revision_guia_id'), table_name='asignaciones_revision')
    op.drop_table('asignaciones_revision')
    op.drop_index(op.f('ix_usuarios_roles_usuario_id'), table_name='usuarios_roles')
    op.drop_index(op.f('ix_usuarios_roles_rol_id'), table_name='usuarios_roles')
    op.drop_table('usuarios_roles')
    op.drop_index(op.f('ix_registro_auditoria_usuario_id'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_creado_en'), table_name='registro_auditoria')
    op.drop_index(op.f('ix_registro_auditoria_accion'), table_name='registro_auditoria')
    op.drop_table('registro_auditoria')
    op.drop_index(op.f('ix_guias_periodo'), table_name='guias')
    op.drop_index(op.f('ix_guias_estado'), table_name='guias')
    op.drop_index(op.f('ix_guias_codigo_banner'), table_name='guias')
    op.drop_index(op.f('ix_guias_autor_id'), table_name='guias')
    op.drop_table('guias')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_roles_codigo'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('facultades')
    # ### end Alembic commands ###
